embedding_size: 64
feat_embed_dim: 64

n_layers: [1, 2]
dropout: [0.3, 0.5]
reg_weight: [0.1, 0.01]
cl_weight: 2.0
consistency_weight: [0.5, 0.1,0.01]
use_neg_sampling: False

hyper_parameters: ["n_layers", "reg_weight", "dropout","consistency_weight"]