embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]
dropout: 0.8

lambda_coeff: 0.9
reg_weight: [0.0, 1e-05, 1e-04, 1e-03]
consistency_weight: [0.5, 0.1,0.01]
noise_level: [0.001,0.0005,0.0001]
n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1

hyper_parameters: ["reg_weight","consistency_weight","noise_level"]